dist: xenial

sudo: required

language: go
go:
  - master

env:
  - GO111MODULE=on

notifications:
  email: false

go_import_path: github.com/pkg/hero-wars


script: 
  - echo "Running the tests!"
  - make build