dist: xenial

sudo: required

language: go
go:
  - 1.11.x

env:
  - GO111MODULE=auto

notifications:
  email: false

go_import_path: github.com/pkg/hero-wars

script: 
  - echo "Running the script"
  - make build