dist: xenial

sudo: required

language: go
go:
  - 1.11.x

env:
  - GO111MODULE=on

notifications:
  email: false

go_import_path: github.com/pkg/hero-wars

script: 
  - echo "Running build and test for Hero Wars"
  - make build
  - make test